name: Test

on:
  push:
    branches:
      - main
      - development
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test
    runs-on: windows-latest
    
    env:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_SCHEMA: explorer-v1-test
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
      DATABASE_POOLING: true

    steps:
      - name: Install .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start PostgreSQL service
        run: |
          $pgService = Get-Service -Name postgresql* -ErrorAction SilentlyContinue
          if ($pgService.Status -ne 'Running') {
              Start-Service -InputObject $pgService
          }
          # Wait until Postgres is ready
          & "C:\Program Files\PostgreSQL\16\bin\pg_isready.exe" -U postgres -d explorer-v1-test

      - name: Restore dependencies
        run: dotnet restore ./src/Explorer.sln

      - name: Build solution
        run: dotnet build ./src/Explorer.sln --no-incremental --configuration Release

      - name: Run tests
        run: dotnet test ./src/Explorer.sln --configuration Release --no-build
